version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
      - "80:80"
      - "443:443"
    volumes:
      - .:/BackEnd
      - /BackEnd/node_modules
    working_dir: /BackEnd
    environment:
      - MONGO_URI=${MONGODB_URI}
    networks:
      - rede_compras

  database:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - rede_compras
    ports:
      - 27017:27017
    environment:
      # Definir o usuário e senha do banco de dados
      #- MONGO_INITDB_ROOT_USERNAME=thiagodiegoli
      #- MONGO_INITDB_ROOT_PASSWORD=pdgjoxtuGQACsPmy
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
      - MONGO_INITDB_ROOT_USERNAME=admin # Comentar quando não for pela aws
      - MONGO_INITDB_ROOT_PASSWORD=adminfatec # Comentar quando não for pela aws
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}

volumes:
  mongo_data:

networks:
  rede_compras:
    driver: bridge
